name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package_and_publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            suffix: 'linux'
          - os: windows-latest
            suffix: 'windows'
    permissions:
      packages: write
      contents: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Zip the binary
        run: |
          mkdir artifact
          cp target/release/racetrace artifact/
          cd artifact
          zip -r racetrace-{{ github.ref_name }}-${{ matrix.suffix }}.zip racetrace
        shell: bash
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifact/racetrace-${{ github.ref_name }}-${{ matrix.suffix }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          make_latest: true
